#!/bin/bash
#
#
#
if [ "$#" -eq 0 ] || [ "$#" -gt 2 ] ; then
    echo Wrong Usage Dummy
else
    if [ "$#" -ge 2 ] ; then
        DIR="$1"
        PATTERN="$2"
        grep -rnw $DIR -i -E -e $PATTERN;
    fi
    
    if [ "$#" -eq 1 ] ; then
        PATTERN="$1"
        grep -rnw ./ -i -E -e $1;
    fi
fi
